version: '3'
networks:
  internal:
    driver: bridge
services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - internal
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - internal
